parser:
  http_server:
    url: "localhost:8080"
  node_checker:
    node_address: "https://cloudflare-eth.com"
    interval_check: 12 # in seconds, 12 is the avg block time in eth.
  storage:
    type: "virtual"

